### PR TITLE
V1 externs

### PR DESCRIPTION
**Pull request by stp59**
I've implemented many of the externs we need, stubbed out unsupported externs with trivial, non-failing implementations, and fixed a few interpreter bugs. 

Some important architecture changes made:
- the signature to `eval` has packet options instead of packets now, to support packet dropping
- `corize` functor adds core externs to a given target. requires a modification to the v1model.mli file (and other targets)
- `State` now treats packets as special stateful objects by putting them in a separate record field. Eval does not know this and uses `packet_location` in vruntime values still.

### CODE REVIEW

**Comment by hackedy** [comment]
These tests pass on master but not in this branch or in the version of it I have merged locally. Can you try merging `master` into `v1-externs` and see if these all still fail?
- examples/checker_tests/good/stack_complex-bmv2.p4
- examples/checker_tests/good/table-entries-exact-bmv2.p4
- examples/checker_tests/good/table-entries-range-bmv2.p4
- stf-test/custom-stf-tests/switch.p4
- stf-test/custom-stf-tests/table3.p4

**Comment by stp59** [comment]
I merged master in and it didn't fix the regression. Do you remember where this was initially fixed? If I can see the commit I can probably fix it quicker.

**Comment by hackedy** [comment]
I think you are looking for the fix-issue-118 branch, which got merged in #119.

**Comment by stp59** [comment]
Pinned it down. This is not a regression, this is exposing a new bug. We added in STF checking that the port numbers are correct at egress as well as the packet. I will need to understand better how the v1 semantics works in order to handle this correctly. In the meantime, I think merging this is fine.

**Pull request merged**
