### PR TITLE
Revert custom bigint

### LINKED ISSUE #54: Non-decimal integer constants lexed incorrectly
The following program
```
const bit<16> IPV4x = 0x0;
const bit<16> IPV4d = 0d0;
const bit<16> IPV4o = 0o0;
const bit<16> IPV4b = 0b0;
const bit<16> IPV4 = 0;
```
is being parsed as
```
const bit<16> IPV4x = 720;
const bit<16> IPV4d = 520;
const bit<16> IPV4o = 630;
const bit<16> IPV4b = 500;
const bit<16> IPV4 = 0;
```
Root cause appears to be the invocation of `Bigint.of_string` by the lexer here: https://github.com/cornell-netlab/petr4/blob/981e36f10ee91ac84c23a8a4f5ad04029fdf9cd2/lib/lexer.mll#L78 which is called from https://github.com/cornell-netlab/petr4/blob/981e36f10ee91ac84c23a8a4f5ad04029fdf9cd2/lib/lexer.mll#L126-L133

### PR DESCRIPTION
**Pull request by alexchang8**
This should fix #54 .

### CODE REVIEW

**Comment by jnfoster** [comment]
Looks good. Go ahead and merge!

**Comment by liujed-intel** [comment]
@alexchang8 I think you'll also need to account for the fact that Jane Street's `Bigint.of_string` doesn't support things of the form `0d0`. Other formats (`0x0`, `0b0`, 0o0`) appear to be fine, however.

**Comment by liujed-intel** [comment]
Then I think this line should be removed: https://github.com/cornell-netlab/petr4/blob/master/lib/lexer.mll#L104

**Comment by jnfoster** [comment]
Let's see how p4lang/p4c#2301 is resolved.

**Pull request merged**
