### PR TITLE
Fix bug in parser for annotations by merging adjacent tokens

### LINKED ISSUE #246: Parser whitespace bug
The parser is adding extra whitespace to annotations. For example @p4runtime_translation("p4.org/psa/v1/PortId_t" , 32) in psa.p4.

### PR DESCRIPTION
**Pull request by jnfoster**
Fixes #246

### CODE REVIEW

**Review by natalieisak — APPROVED** [review]
Fixed the issue! Now the commas are properly spaced. Thanks!

**Comment by jnfoster** [comment]
I didn't add a regression test. Will your pretty-printing roundtripping tests check for this behavior?

**Comment by natalieisak** [comment]
I don't believe so! Should I add that functionality to my test suite?

**Comment by jnfoster** [comment]
That would be awesome!

Btw, you can write a single-line program like this...

```
@annot("Hello World", 42);
const bit<8> x = 0;
```

**Pull request merged**
