### PR TITLE
Fix STF tests

### PR DESCRIPTION
**Pull request by jnfoster**
* The Alcotest predicate `packet_equal` was only checking the output port not the packet
* The STF test harness was confusingly inconsistent in how it represented port-packet pairs. We rationalized it to be (port,packet).
* Note: the STF test harness hides compilation errors -- it maps them to the empty list of packets, which could lead to bugs.
* And just to cap it all off, we currently implement dynamic scope :-/

### CODE REVIEW

**Comment by stp59** [comment]
Actually I just ran the test suite and found that some of the cases are failing because the packet equality check is still case-sensitive for some reason. Is that something we can fix in this PR?

**Comment by jnfoster** [comment]
I think I just addressed the case sensitive issue...

**Comment by rudynicolop** [comment]
Should we change the scoping in this branch? Otherwise it looks good.

**Comment by jnfoster** [comment]
Let's do it in a new branch.

**Pull request merged**
