### PR TITLE
binop type

### PR DESCRIPTION
**Pull request by Harim-H**

### CODE REVIEW

**Comment by jnfoster** [comment]
@pataei is this still useful? It's been pending for ~4 months. Let's either merge it in or delete it...

**Comment by pataei** [comment]
@jnfoster added a review for it just for reference and I'll apply my comments and merge it. Sorry this has been pending for so long.

**Comment by jnfoster** [comment]
Sounds good!

**Comment by pataei** [comment]
After working on this a bit, I'm closing this PR. It contains lots of syntax errors and doesn't even compile. @Harim-H for future reference, you must never commit and push code without compiling it.

**Pull request closed without merging**
