### PR TITLE
Fixes for POPL demo

### PR DESCRIPTION
**Pull request by jnfoster**

### CODE REVIEW

**Comment by hackedy** [comment]
It's failing in CI because of something with changes to p4pp. Not sure what's going on there

**Comment by jnfoster** [comment]
Hmm. We either need to publish a new version of p4pp in Opam, or change petr4 to build p4pp from GitHub...

**Comment by hackedy** [comment]
I fixed the build, but the demo seems to have a deep bug where transition select statements don't work. Not sure what's going on.

```
#include <core.p4>
#include <v1model.p4>

const int MAX_HOPS = 10;
const int STANDARD = 0x00;
const int HOPS = 0x01;

typedef standard_metadata_t std_meta_t;

header byte_t {
    bit<8> byte;
}

struct headers_t {
  byte_t h1;
  byte_t h2;
}

struct meta_t { }

parser MyParser(packet_in pkt, out headers_t hdr, inout meta_t meta, inout std_meta_t std_meta) {
    state start {
        pkt.extract(hdr.h1);
        transition select (8w0) {
            8w0: parse_h2;
            default: accept;
        }
    }
    state parse_h2 {
        pkt.extract(hdr.h2);
        transition accept;
    }
}

control MyVerifyChecksum(inout headers_t hdr, inout meta_t meta) {
    apply { }
}

control MyComputeChecksum(inout headers_t hdr, inout meta_t meta) {
    apply { }
}

control MyIngress(inout headers_t hdr, inout meta_t meta, inout std_meta_t std_meta) {
  apply { }
}

control MyEgress(inout headers_t hdr, inout meta_t meta, inout std_meta_t std_meta) {
    apply { }
}

control MyDeparser(packet_out pkt, in headers_t hdr) {
    apply {
        pkt.emit(hdr.h2);
        pkt.emit(hdr.h1);
    }
}

V1Switch(MyParser(), MyVerifyChecksum(), MyIngress(), MyEgress(), MyComputeChecksum(), MyDeparser()) main;
```
Input packet:
```
01 02
```
Expected output:
```
02 01
```
Actual output is `01 02`.

**Comment by jnfoster** [comment]
I think it may be a bug in the `zarith` bindings...

https://github.com/ocsigen/js_of_ocaml/issues/1070#issuecomment-724470554

What version are you on?

**Comment by hackedy** [comment]
> What version are you on?

Ah, this bug! I forgot. I'm on 0.14, let me upgrade.

**Comment by hackedy** [comment]
Okay, that works now. But the OPAM repository only has v0.14, so I had to install from source.

**Comment by hackedy** [comment]
Okay, whenever ocaml/opam-repository#18254 gets merged and the new version of p4pp shows up on OPAM we can merge this.

**Comment by hackedy** [comment]
Sorry, I have no idea why this Travis build is failing. I can investigate more today.

**Pull request merged**
